<a href="https://colab.research.google.com/github/PisutSukpool/BADS7105-CRM-analytics-and-intelligence/blob/main/Homework%2003/6210422044_PisutSukpool_HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
#!pip install pyxlsb

In [40]:
#!pip install googletrans==3.1.0a0

In [52]:
!pip install pythainlp

Collecting pythainlp
  Downloading https://files.pythonhosted.org/packages/c1/09/1215cb6f6ef0cfc9dbb427a961fda8a47c111955f782f659ca2d38c79adc/pythainlp-2.2.6-py3-none-any.whl (10.6MB)
     |████████████████████████████████| 10.6MB 5.2MB/s
Collecting tinydb>=3.0
  Downloading https://files.pythonhosted.org/packages/e5/7e/85ee672ee60affd5b4461efa19f260cf7575f36b94fbd1f0825742639910/tinydb-4.3.0-py3-none-any.whl
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.6/dist-packages (from pythainlp) (2.23.0)
Collecting python-crfsuite>=0.9.6
  Downloading https://files.pythonhosted.org/packages/95/99/869dde6dbf3e0d07a013c8eebfb0a3d30776334e0097f8432b631a9a3a19/python_crfsuite-0.9.7-cp36-cp36m-manylinux1_x86_64.whl (743kB)
     |████████████████████████████████| 747kB 49.7MB/s
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.22.0->pythainlp) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.22.0->pythainlp) (2020.12.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.22.0->pythainlp) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.22.0->pythainlp) (3.0.4)
Installing collected packages: tinydb, python-crfsuite, pythainlp
Successfully installed pythainlp-2.2.6 python-crfsuite-0.9.7 tinydb-4.3.0

In [41]:
import requests
import pandas as pd
from pyxlsb import convert_date
import numpy as np
from bs4 import BeautifulSoup
url = requests.get('https://github.com/PisutSukpool/BADS7105-CRM-analytics-and-intelligence/tree/main/Homework%2003/Dataset')
soup = BeautifulSoup(url.content, 'html.parser')
div = soup.findAll("span",{"class": "css-truncate css-truncate-target d-block width-fit"})
file_name = []
for i in div:
  if str(i).find('>ac') == -1 and str(i).find('readme') == -1:
    range = str(i)[str(i).find('>Ac')+1:str(i).find('</a>')]
    file_name.append(range)
  elif str(i).find('>ac') != -1 and str(i).find('readme') == -1:
    range = str(i)[str(i).find('>ac')+1:str(i).find('</a>')]
    file_name.append(range)
  else:
    pass

In [42]:
cnt=0
df=pd.DataFrame()
for f in file_name:
  cnt+=1
  f= f.replace(' ','%20')
  try:
    df2 = pd.read_excel('https://github.com/PisutSukpool/BADS7105-CRM-analytics-and-intelligence/raw/main/Homework%2003/Dataset/'+f,names=['Time','Activity','Pain','Gain'])
    df2['User']= cnt
    df2['FileName']  = f
  except: 
    df2 = pd.read_excel('https://github.com/PisutSukpool/BADS7105-CRM-analytics-and-intelligence/raw/main/Homework%2003/Dataset/'+f, engine='pyxlsb',names=['Time','Activity','Pain','Gain'])
    df2['User']= cnt
    df2['FileName']  = f
  df = df.append(df2)
df.index = pd.RangeIndex(len(df.index))

In [43]:
for i,row in df.iterrows():
  if row['FileName'][-1] == 'b':
    df.loc[df.index == i, ['Time']] = convert_date(row['Time'])  
df.head(60)

                   Time  ...                     FileName
0              08:30:00  ...   Acitivities_6210422033.xls
1              08:35:00  ...   Acitivities_6210422033.xls
2              09:00:00  ...   Acitivities_6210422033.xls
3              10:00:00  ...   Acitivities_6210422033.xls
4              10:30:00  ...   Acitivities_6210422033.xls
5              13:00:00  ...   Acitivities_6210422033.xls
6              13:45:00  ...   Acitivities_6210422033.xls
7              14:00:00  ...   Acitivities_6210422033.xls
8              15:15:00  ...   Acitivities_6210422033.xls
9              15:45:00  ...   Acitivities_6210422033.xls
10             19:15:00  ...   Acitivities_6210422033.xls
11             19:30:00  ...   Acitivities_6210422033.xls
12             19:30:00  ...   Acitivities_6210422033.xls
13             20:00:00  ...   Acitivities_6210422033.xls
14             21:00:00  ...   Acitivities_6210422033.xls
15             21:30:00  ...   Acitivities_6210422033.xls
16             22:30:00  ...   Acitivities_6210422033.xls
17             00:00:00  ...   Acitivities_6210422033.xls
18             07:30:00  ...  Acitivities_6210422035.xlsx
19             08:00:00  ...  Acitivities_6210422035.xlsx
20             08:30:00  ...  Acitivities_6210422035.xlsx
21             09:00:00  ...  Acitivities_6210422035.xlsx
22             09:15:00  ...  Acitivities_6210422035.xlsx
23             09:30:00  ...  Acitivities_6210422035.xlsx
24             09:45:00  ...  Acitivities_6210422035.xlsx
25             10:00:00  ...  Acitivities_6210422035.xlsx
26             14:00:00  ...  Acitivities_6210422035.xlsx
27             14:30:00  ...  Acitivities_6210422035.xlsx
28             15:00:00  ...  Acitivities_6210422035.xlsx
29             19:00:00  ...  Acitivities_6210422035.xlsx
30             19:30:00  ...  Acitivities_6210422035.xlsx
31             20:00:00  ...  Acitivities_6210422035.xlsx
32             20:30:00  ...  Acitivities_6210422035.xlsx
33             21:30:00  ...  Acitivities_6210422035.xlsx
34             22:00:00  ...  Acitivities_6210422035.xlsx
35             23:30:00  ...  Acitivities_6210422035.xlsx
36             07:00:00  ...   Acitivities_6220422004.xls
37             07:30:00  ...   Acitivities_6220422004.xls
38             08:30:00  ...   Acitivities_6220422004.xls
39             09:00:00  ...   Acitivities_6220422004.xls
40             10:00:00  ...   Acitivities_6220422004.xls
41             11:00:00  ...   Acitivities_6220422004.xls
42             13:00:00  ...   Acitivities_6220422004.xls
43             14:00:00  ...   Acitivities_6220422004.xls
44             15:00:00  ...   Acitivities_6220422004.xls
45             16:00:00  ...   Acitivities_6220422004.xls
46             17:30:00  ...   Acitivities_6220422004.xls
47             18:30:00  ...   Acitivities_6220422004.xls
48             19:00:00  ...   Acitivities_6220422004.xls
49             21:00:00  ...   Acitivities_6220422004.xls
50             21:30:00  ...   Acitivities_6220422004.xls
51             22:00:00  ...   Acitivities_6220422004.xls
52             00:00:00  ...   Acitivities_6220422004.xls
53             01:00:00  ...   Acitivities_6220422004.xls
54  1900-01-01 06:00:00  ...  Acitivities_6220422011.xlsb
55  1900-01-01 06:30:00  ...  Acitivities_6220422011.xlsb
56  1900-01-01 07:00:00  ...  Acitivities_6220422011.xlsb
57  1900-01-01 07:30:00  ...  Acitivities_6220422011.xlsb
58  1900-01-01 08:00:00  ...  Acitivities_6220422011.xlsb
59  1900-01-01 08:30:00  ...  Acitivities_6220422011.xlsb

[60 rows x 6 columns]

In [44]:
df['Seq_Activities']=df.groupby('User').cumcount()
df['Time'] = df['Time'].apply(str)
df['Time_Cls'] = df['Time']
df.head(60)
for ind , row in df.iterrows():
  row_time=row['Time_Cls'].strip().strip(' ').strip('m').strip('a').strip('p').strip(' ')
  if row_time.count(':') == 2 and len(row_time)== 8:   #08:30:00
    df.loc[df.index == ind, ['Time_Cls']] =  row_time[:row_time.find(':')] + row_time[row_time.find(':'):row_time.find(':',3)]

  elif row_time.count(':') == 2 and len(row_time)!= 8: # 1/1/1900  6:00:00 AM
    df.loc[df.index == ind, ['Time_Cls']] = row_time[row_time.find(':')-2 : row_time.find(':',row_time.find(':')-2+3)]

  elif row_time.count(':') == 1 and len(row_time) == 4:   #8:00
    df.loc[df.index == ind, ['Time_Cls']] = '0'+row_time

  elif row_time.count(':') == 1 and len(row_time) != 4:   #08:00
    df.loc[df.index == ind, ['Time_Cls']] = row_time

  elif row_time.count('.') == 1 and len(row_time[:row_time.find('.')]) == 2 and len(row_time[row_time.find('.')+1:]) == 2:  # 13.15
    df.loc[df.index == ind, ['Time_Cls']] = row_time[:row_time.find('.')]+':'+row_time[row_time.find('.')+1:]

  elif row_time.count('.') == 1 and len(row_time[:row_time.find('.')]) == 1 and len(row_time[row_time.find('.')+1:]) == 2:  # 3.15
    df.loc[df.index == ind, ['Time_Cls']] = '0'+row_time[:row_time.find('.')]+':'+row_time[row_time.find('.')+1:]

  elif row_time.count('.') == 1 and len(row_time[:row_time.find('.')]) == 1 and len(row_time[row_time.find('.')+1:]) == 1:  # 3.1
    df.loc[df.index == ind, ['Time_Cls']] = '0'+row_time[:row_time.find('.')]+':'+row_time[row_time.find('.')+1:]+'0'

  elif row_time.count('.') == 1 and len(row_time[:row_time.find('.')]) == 2 and len(row_time[row_time.find('.')+1:]) == 1:  # 13.1
    df.loc[df.index == ind, ['Time_Cls']] = row_time[:row_time.find('.')]+':'+row_time[row_time.find('.')+1:]+'0'

  elif row_time.count('.') == 0 and row_time.count(':') == 0 and len(row_time)==1: #1 
    df.loc[df.index == ind, ['Time_Cls']] = '0'+row_time+':00'

  elif row_time.count('.') == 0 and row_time.count(':') == 0 and len(row_time)==2: #12
    df.loc[df.index == ind, ['Time_Cls']] = row_time+':00'    

  elif row_time.count('.') == 0 and row_time.count(':') == 0 and len(row_time)==3: #800
    df.loc[df.index == ind, ['Time_Cls']] = '0'+row_time[0]+':'+row_time[1:]  

  elif row_time.count('.') == 0 and row_time.count(':') == 0 and len(row_time)==4: #0630
    df.loc[df.index == ind, ['Time_Cls']] = row_time[:2]+':'+row_time[2:]

In [45]:
df["Activity"]= df["Activity"].str.replace("\.", "", case = False) 
df["Pain"]= df["Pain"].str.replace("\.", "", case = False) 
df["Gain"]= df["Gain"].str.replace("\.", "", case = False) 
df.to_excel('test.xlsx')

In [46]:
from googletrans import Translator
import string
ls_en = list(string.ascii_lowercase)
translator = Translator()
df['Activity'] = df['Activity'].astype(str).apply(translator.translate, src='en', dest='th').apply(getattr, args=('text',))
df['Pain'] = df['Pain'].astype(str).apply(translator.translate, src='en', dest='th').apply(getattr, args=('text',))
df['Gain'] = df['Gain'].astype(str).apply(translator.translate, src='en', dest='th').apply(getattr, args=('text',))
df_th = df.copy()
df_th

         Time                     Activity  ... Seq_Activities Time_Cls
0    08:30:00                      ตื่นนอน  ...              0    08:30
1    08:35:00                       อาบน้ำ  ...              1    08:35
2    09:00:00                  กินอาหาเช้า  ...              2    09:00
3    10:00:00      เดินทางด้วย BTS ไปทำงาน  ...              3    10:00
4    10:30:00       ถึงที่ทำงาน เริ่มทำงาน  ...              4    10:30
..        ...                          ...  ...            ...      ...
909      20.0                       อาบน้ำ  ...              9    20:00
910      20.2    เดินไปที่ตู้เย็น หานมดื่ม  ...             10    20:20
911      20.3  เล่น social หาเพลงที่ชอบฟัง  ...             11    20:30
912      21.3                ทำการบ้าน ปโท  ...             12    21:30
913      23.3           สวดมนต์ และเข้านอน  ...             13    23:30

[914 rows x 8 columns]

In [53]:
from pythainlp import word_tokenize # ทำการเรียกตัวตัดคำ
from pythainlp.word_vector import * # ทำการเรียก thai2vec
from sklearn.metrics.pairwise import cosine_similarity  # ใช้หาค่าความคล้ายคลึง
import numpy as np
model=get_model() # ดึง model ของ thai2vec มาเก็บไว้ในตัวแปร model
def sentence_vectorizer(ss,dim=300,use_mean=True): # ประกาศฟังก์ชัน sentence_vectorizer
    s = word_tokenize(ss)
    vec = np.zeros((1,dim))
    for word in s:
        if word in model.wv.index2word:
            vec+= model.wv.word_vec(word)
        else: pass
    if use_mean: vec /= len(s)
    return vec
def sentence_similarity(s1,s2):
    return cosine_similarity(sentence_vectorizer(str(s1)),sentence_vectorizer(str(s2)))

Corpus: thai2fit_wv
- Downloading: thai2fit_wv 0.1

100%|██████████| 62452646/62452646 [00:00<00:00, 82600614.94it/s]

In [67]:
df["Type_Day"] = df['Activity'].str.extract('(ทำงาน|work|Work)')[0]
df_work = df[['User', 'Type_Day']].copy()
df_work = df_work.drop_duplicates()
df_work = df_work.replace({'Type_Day': {'work': 'ทำงาน', 'Work': 'ทำงาน'}})
df_work = df_work.drop(df_work[df_work.Type_Day != 'ทำงาน'].index)
df_work = df_work.drop_duplicates()
df_work.head(60)

     User Type_Day
3       1    ทำงาน
21      2    ทำงาน
41      3    ทำงาน
57      4    ทำงาน
78      5    ทำงาน
97      6    ทำงาน
111     7    ทำงาน
126     8    ทำงาน
146     9    ทำงาน
167    10    ทำงาน
189    11    ทำงาน
204    12    ทำงาน
224    13    ทำงาน
238    14    ทำงาน
268    15    ทำงาน
292    17    ทำงาน
331    19    ทำงาน
357    20    ทำงาน
389    21    ทำงาน
401    22    ทำงาน
419    23    ทำงาน
456    25    ทำงาน
474    26    ทำงาน
492    27    ทำงาน
518    28    ทำงาน
537    29    ทำงาน
574    31    ทำงาน
605    33    ทำงาน
640    34    ทำงาน
666    35    ทำงาน
684    36    ทำงาน
704    37    ทำงาน
746    39    ทำงาน
765    40    ทำงาน
782    41    ทำงาน
794    42    ทำงาน
819    43    ทำงาน
838    44    ทำงาน
859    45    ทำงาน
881    46    ทำงาน
901    47    ทำงาน

In [70]:
df2 = df.merge(df_work, on='User', how='left')
df2

         Time                     Activity  ... Type_Day_x Type_Day_y
0    08:30:00                      ตื่นนอน  ...        NaN      ทำงาน
1    08:35:00                       อาบน้ำ  ...        NaN      ทำงาน
2    09:00:00                  กินอาหาเช้า  ...        NaN      ทำงาน
3    10:00:00      เดินทางด้วย BTS ไปทำงาน  ...      ทำงาน      ทำงาน
4    10:30:00       ถึงที่ทำงาน เริ่มทำงาน  ...      ทำงาน      ทำงาน
..        ...                          ...  ...        ...        ...
909      20.0                       อาบน้ำ  ...        NaN      ทำงาน
910      20.2    เดินไปที่ตู้เย็น หานมดื่ม  ...        NaN      ทำงาน
911      20.3  เล่น social หาเพลงที่ชอบฟัง  ...        NaN      ทำงาน
912      21.3                ทำการบ้าน ปโท  ...        NaN      ทำงาน
913      23.3           สวดมนต์ และเข้านอน  ...        NaN      ทำงาน

[914 rows x 10 columns]

['a', 'b', 'c', ' ', '2', '.', '3']